### PR TITLE
Revert "setting image for container in generator"

### PR DESCRIPTION
**Pull request by manute**
Reverts InVisionApp/kit-deploymentizer#72

We want to have a version of this lib for testing this image branch for a while -- but we don't want to deploy it yet and either stop the dev cycle 
(this could be solved with feature-flags but actually we don't have one)

### CODE REVIEW

**Comment by manute** [comment]
Also it's failing because when we have a service with 2 containers it's passing in the same commit to the 2 images causing `ImagePullBackOff` for the second image.

```Containers:
  testrosie-snowflake-con:
    Container ID:	docker://d2b60b9daed51215ebbeb6b43bf928c9b644bf283d391578261ab28580bba4ea
    Image:		quay.io/invision/node-testrosie-snowflake:release-177912a552de2b8efed731ca9373a89ee69175a9
    Image ID:		docker-pullable://quay.io/invision/node-testrosie-snowflake@sha256:8675302618a4bd19be37007933e614628350b4793355095cdbe6b3e7c6653708
    Port:		80/TCP
    State:		Running
      Started:		Wed, 21 Mar 2018 12:12:31 +0100
    Ready:		True
    Restart Count:	0
    Limits:
      cpu:	200m
      memory:	128Mi
    Requests:
      cpu:	50m
      memory:	64Mi
    Liveness:	http-get http://:80/healthcheck delay=30s timeout=3s period=10s #success=1 #failure=3
    Readiness:	http-get http://:80/healthcheck delay=20s timeout=2s period=10s #success=1 #failure=1
    Environment:
      CRASH_AFTER_SECONDS:	0
      GET_HOSTS_FROM:		dns
      PORT:			80
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-8z6bs (ro)
  testrosie-con:
    Container ID:
    Image:		quay.io/invision/node-test-rosie:release-177912a552de2b8efed731ca9373a89ee69175a9
    Image ID:
    Port:		<none>
    State:		Waiting
      Reason:		ImagePullBackOff```

But I don't know how to solve this 🤔 , maybe skipping the process in that case ??

**Comment by chrisfjones** [comment]
An ENV_VAR feature flag would work for this too

**Comment by c1freitas** [comment]
@manute Lets figure out a solution for this tomorrow. Can you propose a few suggestions?

**Comment by manute** [comment]
Well my suggestions are based on what I know regarding the kit code , so they could be limited. 
Having said that , my suggestions are: 
1. Don´t touch the  yaml in coreos of the deployments and skip that process for services that have more than one container (As we have only a few cases)
2. Touch the deployment yaml files of the services that have more than one container, adding the properties of `image_name` and `image_branch` because each container can have different name for quay

**Comment by c1freitas** [comment]
We can't just skip the ones with greater than 1 container since it would not get the correct SHA when deploying. 

What do you think about adding an attribute `primary`:
```

  eventbus-kafka:
    containers:
      eventbus-kafka-con:
        primary:true
        image_tag: invision/eventbus-kafka
        name: eventbus-kafka
      eventbus-kafka-datadog-con:
       primary: false
      ...
```
And if container.length > 1 and primary == undefined we throw an error?

https://github.com/InVisionApp/kubernetes-coreos/blob/master/manifests/base-cluster.yaml#L1766

We would need to then check for `primary` in that `deploymentizer` code

**Comment by manute** [comment]
yeah it could work

**Comment by manute** [comment]
correct me if I´m wrong but there´re some resources with different names/image_tag in their mustache file no?

**Comment by erutherford** [comment]
yeah, you're probably right.

**Pull request merged**
