### PR TITLE
minor: refactored to work with v2 of the env-api. 

### PR DESCRIPTION
**Pull request by c1freitas**
# What
Updated to call v2 endpoint of env-api. This version will return specific errors for values not found. These errors are then passed up the call stack.

There is now 2 versions of this plugin. v2 works with the new endpoints and can be enabled in the `kit.yaml`

### CODE REVIEW

**Comment by c1freitas** [comment]
I have this as semver: minor, it is a breaking change but only for the env-api - I feel this plugin should not even be part of this repo....

**Comment by c1freitas** [comment]
Also, this will cause any failure to halt processing for all clusters. For example, currently `cfproejcts` can not be deployed to any testing environments, since it fails for one cluster. We also will not have any visibility into the testing cluster failures at this point :(

**Comment by chesleybrown** [comment]
As discussed recommend making a v2 plugin so this can remain backwards-compatible.

**Comment by chesleybrown** [comment]
All good. We plan to eventually move these plugins out of this repo so I think it's fine to merge as is.

**Pull request merged**
